name: geoplanar_docs
channels:
- conda-forge
dependencies:
- python
# dependencies
- geopandas
- libpysal
- numpy
- geopy
- matplotlib-base
- mercantile
- pillow
- rasterio
- requests
- joblib
- pip
# doc dependencies
- sphinx
- numpydoc
- ipython
- sphinx-book-theme
- myst-nb